### ISSUE TITLE
Error in MAX31855 when using HWSPI on STM32

### ISSUE THREAD

**Issue by Bibbbi** [RobTillaart/MAX31855_RT#14]
When I use the original Max31855 library v0.2.4 the temperature display is not correct. (is to high)

**Hardware:** STM32DUINO STM32F405RGT6 
https://www.tindie.com/products/icstation/stm32f4-micropython-stm32-pyboard-module11882/

**Hardware SPI:** 
PA7  // SPI1_MOSI
PA6  // SPI1_MISO
PA5  // SPI1_SCLK
PA4  // SPI1_SS

![Temperature not correct](https://user-images.githubusercontent.com/34800528/124365763-5499fa80-dc4a-11eb-8f27-ca4295fc7cbe.jpg)

I changed the source code as follows and the temeprature display was correct.

![Temperature correct](https://user-images.githubusercontent.com/34800528/124365786-857a2f80-dc4a-11eb-9f94-e43ea7ca3f8a.jpg)

**MAX31855.cpp**
```
uint32_t MAX31855::_read(void)
{
  _rawData = 0;
  
  if (_hwSPI)
  {
    SPI.beginTransaction(SPISettings(16000000, MSBFIRST, SPI_MODE0));
    digitalWrite(_cs, LOW);
	
    for (uint8_t i = 0; i < 4; i++)
    {
      _rawData <<= 8;
      _rawData += SPI.transfer(0);
    }
    digitalWrite(_cs, HIGH);
    SPI.endTransaction();
  }
  else
  {
    digitalWrite(_cs, LOW);
    for (int8_t i = 31; i >= 0; i--)
    {
      _rawData <<= 1;
      digitalWrite(_sclk, LOW);
      // delayMicroseconds(1);  // DUE
      if ( digitalRead(_miso) ) _rawData++;
      digitalWrite(_sclk, HIGH);
      // delayMicroseconds(1);  // DUE
    }
    digitalWrite(_cs, HIGH);
  }
  return _rawData;
}
```
The CS signal must be between SPI.beginTransaction and SPI.endTransaction. Can anyone confirm this?

**Comment by RobTillaart** [comment]
Thanks for the issue, 
might take several days before I have time to investigate.  I do not have an STM32, so I have to check e.g ESP32.

It looks like a missing/extra pulse as the value seems x2   
Note: exponent of IEEE754 float is power of 2.

Can you confirm that the software SPI works?

**Comment by Bibbbi** [comment]
yes,  the software SPI works fine.

**Comment by RobTillaart** [comment]
Good to hear SWSPI part is working.

<thinking out loud>

Technically if there is only one device it should be possible to connect the CS line to GND permanently. 
The SPI protocol should allow that.

looking at your log, I notice that the **RAW** value shows 26 bits (wrong value) and 25 bits (right value). 
It does not show the leading zero's - and it needs "byte separators"  [TODO]

The raw value (lower 11 bits of raw) is the temperature in steps of 0.0625°C  (1/16th)
As this value is shifted one position to the right, one will get a temperature that is exactly a factor 2 too high. 

So it appears that **SPI.beginTransaction(SPISettings(16000000, MSBFIRST, SPI_MODE0));** does trigger the sending of the first bit if the CS line is already LOW on the STM platform.

On AVR, UNO the library 0.2.4 works, but of course the low level HW SPI is different.
Your solution works too on a AVR, UNO.

Need to find a free ESP32 to test.

**Comment by RobTillaart** [comment]
Created a develop branch / PR with your modifications plus some minor updates.

Tested with an ESP32 and an UNO at different SPI hardware speeds and works well.
Can you confirm the develop branch works with the STM32?

Thanks,
Rob

**Comment by RobTillaart** [comment]
ESP32 run
![image](https://user-images.githubusercontent.com/462844/124395493-b3bc4580-dd04-11eb-9655-c3a84456f18a.png)

**Comment by Bibbbi** [comment]
I used your development branch
https://github.com/RobTillaart/MAX31855_RT/tree/develop

Tested with a STM32F405RGT6 at various SPI hardware speeds and works fine.
I can confirm that the development branch works with the STM32.

![STM32 Developer Version Temperature correct](https://user-images.githubusercontent.com/34800528/124399737-b37c7400-dd1d-11eb-832a-2a346ea1b87a.jpg)

**Comment by RobTillaart** [comment]
Thanks
Then I will merge later today.
